# Generated by Django 5.2.17 on 2026-09-26 10:47

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_instagrampost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_posts/'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='instagram_url',
            field=models.URLField(help_text='Paste the URL of a public Instagram post, Reel, or video.', validators=[store.models.validate_instagram_post_url]),
        ),
    ]
